-- MySQL Script generated by MySQL Workbench
-- Mon Jun  9 07:02:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_paymybuddy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_paymybuddy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_paymybuddy` DEFAULT CHARACTER SET utf8 ;
USE `db_paymybuddy` ;

-- -----------------------------------------------------
-- Table `db_paymybuddy`.`comptes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paymybuddy`.`comptes` (
  `compte_id` INT NOT NULL AUTO_INCREMENT,
  `solde` DOUBLE NOT NULL,
  `fk_compte_id_user` INT NOT NULL,
  PRIMARY KEY (`compte_id`),
  INDEX `fk_comptes_users1_idx` (`fk_compte_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_comptes_users1`
    FOREIGN KEY (`fk_compte_id_user`)
    REFERENCES `db_paymybuddy`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_paymybuddy`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paymybuddy`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `fk_user_id_compte` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_comptes1_idx` (`fk_user_id_compte` ASC) VISIBLE,
  CONSTRAINT `fk_users_comptes1`
    FOREIGN KEY (`fk_user_id_compte`)
    REFERENCES `db_paymybuddy`.`comptes` (`compte_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_paymybuddy`.`connections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paymybuddy`.`connections` (
  `fk_connection_first_id_user` INT NOT NULL,
  `fk_connection_second_id_user` INT NOT NULL,
  INDEX `fk_connections_users_idx` (`fk_connection_first_id_user` ASC) VISIBLE,
  INDEX `fk_connections_users1_idx` (`fk_connection_second_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_connections_users`
    FOREIGN KEY (`fk_connection_first_id_user`)
    REFERENCES `db_paymybuddy`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_connections_users1`
    FOREIGN KEY (`fk_connection_second_id_user`)
    REFERENCES `db_paymybuddy`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_paymybuddy`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paymybuddy`.`transactions` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `amount` DOUBLE NOT NULL,
  `fk_transaction_id_compte_sender` INT NOT NULL,
  `fk_transaction_id_compte_reciever` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `fk_transactions_comptes1_idx` (`fk_transaction_id_compte_sender` ASC) VISIBLE,
  INDEX `fk_transactions_comptes2_idx` (`fk_transaction_id_compte_reciever` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_comptes1`
    FOREIGN KEY (`fk_transaction_id_compte_sender`)
    REFERENCES `db_paymybuddy`.`comptes` (`compte_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_comptes2`
    FOREIGN KEY (`fk_transaction_id_compte_reciever`)
    REFERENCES `db_paymybuddy`.`comptes` (`compte_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
