-- MySQL Script generated by MySQL Workbench
-- Wed Jun 11 18:49:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -- -----------------------------------------------------
-- Schema paymybuddy_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema paymybuddy_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paymybuddy_db` DEFAULT CHARACTER SET utf8 ;
USE `paymybuddy_db` ;

-- -----------------------------------------------------
-- Table `paymybuddy_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;

----
---- Dumping data for table `users`
----
----
LOCK TABLES `users` WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`last_name`, `first_name`, `email`, `password`) VALUES
('Jean', 'Krys', 'jean@yahoo.fr', 'Jean_69'),
('Philipe', 'Clar', 'clar@yahoo.fr', 'coucou_525'),
('Alice', 'Assy', 'alice@yahoo.fr', 'lolo-2020');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `paymybuddy_db`.`connections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`connections` (
  `id_connection` INT NOT NULL AUTO_INCREMENT,
  `date_connection` DATETIME NOT NULL,
  `fk_id_user_owner` INT NOT NULL,
  `fk_id_user_friend` INT NOT NULL,
  INDEX `fk_connections_users_idx` (`fk_id_user_owner` ASC) VISIBLE,
  INDEX `fk_connections_users1_idx` (`fk_id_user_friend` ASC) VISIBLE,
  PRIMARY KEY (`id_connection`),
  CONSTRAINT `fk_connections_users`
    FOREIGN KEY (`fk_id_user_owner`)
    REFERENCES `paymybuddy_db`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_connections_users1`
    FOREIGN KEY (`fk_id_user_friend`)
    REFERENCES `paymybuddy_db`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`comptes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`comptes` (
  `id_compte` INT NOT NULL AUTO_INCREMENT,
  `solde` DOUBLE NOT NULL,
  `fk_id_user` INT NOT NULL,
  PRIMARY KEY (`id_compte`),
  INDEX `fk_comptes_users1_idx` (`fk_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_comptes_users1`
    FOREIGN KEY (`fk_id_user`)
    REFERENCES `paymybuddy_db`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

----
---- Dumping data for table `comptes`
----
----
LOCK TABLES `comptes` WRITE;
/*!40000 ALTER TABLE `comptes` DISABLE KEYS */;
INSERT INTO `paymybuddy_db`.`comptes` (`solde`, `fk_id_user`)
VALUES (1700.50, 1), (2050.00, 2), (705.25, 3);
/*!40000 ALTER TABLE `comptes` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `paymybuddy_db`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`transactions` (
  `id_transaction` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `amount` DOUBLE NOT NULL,
  `date_transaction` DATETIME NOT NULL,
  `fk_id_compte_sender` INT NOT NULL,
  `fk_id_compte_reciever` INT NOT NULL,
  PRIMARY KEY (`id_transaction`),
  INDEX `fk_transactions_comptes1_idx` (`fk_id_compte_sender` ASC) VISIBLE,
  INDEX `fk_transactions_comptes2_idx` (`fk_id_compte_reciever` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_comptes1`
    FOREIGN KEY (`fk_id_compte_sender`)
    REFERENCES `paymybuddy_db`.`comptes` (`id_compte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_comptes2`
    FOREIGN KEY (`fk_id_compte_reciever`)
    REFERENCES `paymybuddy_db`.`comptes` (`id_compte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
